sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t vincent3333/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vincent3333/docker-tract npm run test -- --coverage